// src/lib/components/common/DownloadBackupButton.svelte
<script lang="ts">
	import { Button } from '$lib/components/ui/button';
	import { backupFilename } from '$lib/brand';
	import { toast } from '$lib/toast';
	import { CheckCircle2, Download, Loader2 } from 'lucide-svelte';

	interface Props {
		variant?: 'default' | 'outline' | 'ghost';
		size?: 'default' | 'sm' | 'lg' | 'icon';
		class?: string;
		showLabel?: boolean;
	}

	let {
		variant = 'outline',
		size = 'default',
		class: className,
		showLabel = true
	}: Props = $props();

	let isDownloading = $state(false);
	let justDownloaded = $state(false);

	async function handleDownload() {
		isDownloading = true;
		justDownloaded = false;

		try {
			const response = await fetch('/api/backup?download=true');
			if (!response.ok) {
				const error = await response.json();
				throw new Error(error.error || 'Failed to create backup');
			}

			const contentDisposition = response.headers.get('Content-Disposition');
			let filename = backupFilename(new Date());
			if (contentDisposition) {
				const match = contentDisposition.match(/filename="(.+)"/);
				if (match) filename = match[1];
			}

			const blob = await response.blob();
			const url = window.URL.createObjectURL(blob);
			const link = document.createElement('a');
			link.href = url;
			link.download = filename;
			document.body.appendChild(link);
			link.click();
			document.body.removeChild(link);
			window.URL.revokeObjectURL(url);

			justDownloaded = true;
			toast.success('Backup downloaded', { description: `Saved as ${filename}` });
			setTimeout(() => {
				justDownloaded = false;
			}, 3000);
		} catch (error) {
			console.error('Error downloading backup:', error);
			toast.error(
				'Failed to download backup',
				{ description: error instanceof Error ? error.message : 'Unknown error' }
			);
		} finally {
			isDownloading = false;
		}
	}
</script>

<Button {variant} {size} class={className} disabled={isDownloading} onclick={handleDownload}>
	{#if isDownloading}
		<Loader2 class="h-4 w-4 animate-spin" />
	{:else if justDownloaded}
		<CheckCircle2 class="h-4 w-4 text-green-500" />
	{:else}
		<Download class="h-4 w-4" />
	{/if}
	{#if showLabel}
		<span class="ml-2">
			{isDownloading ? 'Downloading...' : justDownloaded ? 'Downloaded!' : 'Download Backup'}
		</span>
	{/if}
</Button>

// components/common/download-backup-button.tsx
'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Download, Loader2, CheckCircle2 } from 'lucide-react';
import { toast } from 'sonner';
import { backupFilename } from '@/lib/brand';

interface DownloadBackupButtonProps {
  variant?: 'default' | 'outline' | 'ghost';
  size?: 'default' | 'sm' | 'lg' | 'icon';
  className?: string;
  showLabel?: boolean;
}

export function DownloadBackupButton({
  variant = 'outline',
  size = 'default',
  className,
  showLabel = true,
}: DownloadBackupButtonProps) {
  const [isDownloading, setIsDownloading] = useState(false);
  const [justDownloaded, setJustDownloaded] = useState(false);

  const handleDownload = async () => {
    setIsDownloading(true);
    setJustDownloaded(false);

    try {
      const response = await fetch('/api/backup?download=true');

      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.error || 'Failed to create backup');
      }

      // Get the filename from the Content-Disposition header or generate one
      const contentDisposition = response.headers.get('Content-Disposition');
      let filename = backupFilename(new Date());

      if (contentDisposition) {
        const match = contentDisposition.match(/filename="(.+)"/);
        if (match) {
          filename = match[1];
        }
      }

      // Create blob and download
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = filename;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);

      setJustDownloaded(true);
      toast.success('Backup downloaded successfully', {
        description: `Saved as ${filename}`,
      });

      // Reset the checkmark after 3 seconds
      setTimeout(() => {
        setJustDownloaded(false);
      }, 3000);
    } catch (error) {
      console.error('Error downloading backup:', error);
      toast.error('Failed to download backup', {
        description: error instanceof Error ? error.message : 'Unknown error',
      });
    } finally {
      setIsDownloading(false);
    }
  };

  const getIcon = () => {
    if (isDownloading) {
      return <Loader2 className="h-4 w-4 animate-spin" />;
    }
    if (justDownloaded) {
      return <CheckCircle2 className="h-4 w-4 text-green-500" />;
    }
    return <Download className="h-4 w-4" />;
  };

  return (
    <Button
      variant={variant}
      size={size}
      onClick={handleDownload}
      disabled={isDownloading}
      className={className}
    >
      {getIcon()}
      {showLabel && (
        <span className="ml-2">
          {isDownloading
            ? 'Downloading...'
            : justDownloaded
              ? 'Downloaded!'
              : 'Download Backup'}
        </span>
      )}
    </Button>
  );
}
