// app/dashboard/page.tsx
import { db } from '@/db';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import {
  calculateTotalPrincipal,
  calculateTotalInterest,
  calculateInvestorStats,
} from '@/lib/calculations';
import {
  SummaryCard,
  DashboardActivityCards,
  PageHeader,
  OverdueChecker,
} from '@/components/common';
import dynamic from 'next/dynamic';

const CurrencyBarChart = dynamic(() =>
  import('@/components/common/charts/currency-bar-chart').then(
    (m) => m.CurrencyBarChart,
  ),
);
const LoanTypePieChart = dynamic(() =>
  import('@/components/common/charts/loan-type-pie-chart').then(
    (m) => m.LoanTypePieChart,
  ),
);
const CashflowTrendChart = dynamic(() =>
  import('@/components/common/charts/cashflow-trend-chart').then(
    (m) => m.CashflowTrendChart,
  ),
);
import type { LoanType } from '@/lib/types';
import {
  format,
  subWeeks,
  subDays,
  subMonths,
  startOfWeek,
  endOfWeek,
  startOfDay,
  endOfDay,
  startOfMonth,
  endOfMonth,
  addDays,
  isBefore,
  isAfter,
  isFuture,
  isPast,
} from 'date-fns';
import { getCachedAuth } from '@/auth';
import { SHOW_TRANSACTIONS_UI } from '@/lib/feature-flags';
import { eq } from 'drizzle-orm';
import { loans, investors, transactions, loanInvestors } from '@/db/schema';
import { cn } from '@/lib/utils';
import { unstable_cache } from 'next/cache';
import { CACHE_TAGS } from '@/lib/cache-invalidation';

async function queryDashboardData(userId: string) {
  try {
    // Fire independent queries in parallel
    const [ownedLoans, investorRecord, ownedInvestors] = await Promise.all([
      db.query.loans.findMany({
        where: eq(loans.userId, userId),
        with: {
          loanInvestors: {
            with: {
              investor: true,
              interestPeriods: true,
              receivedPayments: true,
            },
          },
          transactions: {
            orderBy: (transactions, { desc }) => [desc(transactions.date)],
          },
        },
      }),
      db.query.investors.findFirst({
        where: eq(investors.investorUserId, userId),
      }),
      db.query.investors.findMany({
        where: eq(investors.userId, userId),
        with: {
          loanInvestors: {
            with: {
              loan: true,
              interestPeriods: true,
            },
          },
          transactions: {
            orderBy: (transactions, { desc }) => [desc(transactions.date)],
          },
        },
      }),
    ]);

    // Shared data queries (depend on investorRecord)
    let sharedLoans: any[] = [];
    let sharedInvestors: any[] = [];
    let allTransactions;

    if (investorRecord) {
      const [sharedLoanInvestments, sharedInvestorLoanInvestments, txns] =
        await Promise.all([
          db.query.loanInvestors.findMany({
            where: eq(loanInvestors.investorId, investorRecord.id),
            with: {
              loan: {
                with: {
                  loanInvestors: {
                    with: {
                      investor: true,
                      interestPeriods: true,
                      receivedPayments: true,
                    },
                  },
                  transactions: {
                    orderBy: (transactions, { desc }) => [
                      desc(transactions.date),
                    ],
                  },
                },
              },
            },
          }),
          db.query.loanInvestors.findMany({
            where: eq(loanInvestors.investorId, investorRecord.id),
            with: {
              loan: {
                with: {
                  loanInvestors: {
                    with: {
                      investor: {
                        with: {
                          loanInvestors: {
                            with: {
                              loan: true,
                              interestPeriods: true,
                            },
                          },
                          transactions: {
                            orderBy: (transactions, { desc }) => [
                              desc(transactions.date),
                            ],
                          },
                        },
                      },
                    },
                  },
                },
              },
            },
          }),
          db.query.transactions.findMany({
            where: (transactions, { eq, or }) =>
              or(
                eq(transactions.userId, userId),
                eq(transactions.investorId, investorRecord.id),
              ),
            with: {
              investor: true,
              loan: true,
            },
            orderBy: (transactions, { desc }) => [desc(transactions.date)],
          }),
        ]);

      sharedLoans = sharedLoanInvestments.map((li) => li.loan);
      allTransactions = txns;

      const investorSet = new Set();
      sharedInvestorLoanInvestments.forEach((li) => {
        li.loan.loanInvestors.forEach((loanInv) => {
          if (!investorSet.has(loanInv.investor.id)) {
            investorSet.add(loanInv.investor.id);
            sharedInvestors.push(loanInv.investor);
          }
        });
      });
    } else {
      allTransactions = await db.query.transactions.findMany({
        where: eq(transactions.userId, userId),
        with: {
          investor: true,
          loan: true,
        },
        orderBy: (transactions, { desc }) => [desc(transactions.date)],
      });
    }

    // Combine and deduplicate loans
    const loansMap = new Map();
    [...ownedLoans, ...sharedLoans].forEach((loan) => {
      loansMap.set(loan.id, loan);
    });
    const allLoans = Array.from(loansMap.values()).sort(
      (a, b) =>
        new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime(),
    );

    // Combine and deduplicate investors
    const investorsMap = new Map();
    [...ownedInvestors, ...sharedInvestors].forEach((investor) => {
      investorsMap.set(investor.id, investor);
    });
    const allInvestors = Array.from(investorsMap.values());

    // Calculate loan statistics
    const totalPrincipal = allLoans.reduce(
      (sum, loan) => sum + calculateTotalPrincipal(loan.loanInvestors),
      0,
    );

    // Calculate completed principal (only from completed loans)
    const completedLoansData = allLoans.filter(
      (loan) => loan.status === 'Completed',
    );
    const completedPrincipal = completedLoansData.reduce(
      (sum, loan) => sum + calculateTotalPrincipal(loan.loanInvestors),
      0,
    );

    // Calculate interest earned from completed loans only
    const completedInterestEarned = completedLoansData.reduce(
      (sum, loan) => sum + calculateTotalInterest(loan.loanInvestors),
      0,
    );

    // Calculate total interest (expected from all loans)
    const totalInterestExpected = allLoans.reduce(
      (sum, loan) => sum + calculateTotalInterest(loan.loanInvestors),
      0,
    );

    const activeLoansCount = allLoans.filter(
      (loan) =>
        loan.status === 'Fully Funded' || loan.status === 'Partially Funded',
    ).length;

    const completedLoansCount = completedLoansData.length;

    const overdueLoansCount = allLoans.filter(
      (loan) => loan.status === 'Overdue',
    ).length;

    // Calculate investor statistics
    const totalInvestors = allInvestors.length;
    const activeInvestors = allInvestors.filter((inv) =>
      inv.loanInvestors.some(
        (li: any) =>
          li.loan.status === 'Fully Funded' ||
          li.loan.status === 'Partially Funded',
      ),
    ).length;

    // Calculate transaction statistics
    const totalInflow = allTransactions
      .filter((t) => t.direction === 'In')
      .reduce((sum, t) => sum + parseFloat(t.amount), 0);

    const totalOutflow = allTransactions
      .filter((t) => t.direction === 'Out')
      .reduce((sum, t) => sum + parseFloat(t.amount), 0);

    // Helper function to check if a transaction qualifies as valid inflow
    // Inflow is only valid if:
    // - No loan attached (general investment transaction), OR
    // - Loan is attached AND loan status is 'Completed' (paid on time, not overdue)
    const isValidInflow = (t: (typeof allTransactions)[0]) => {
      if (t.direction !== 'In') return false;
      // If no loan attached, it's a general transaction - count as inflow
      if (!t.loan) return true;
      // If loan is attached, only count if loan is completed (paid)
      return t.loan.status === 'Completed';
    };

    // Calculate daily trend data (last 14 days)
    const dailyData = [];
    for (let i = 13; i >= 0; i--) {
      const dayDate = subDays(new Date(), i);
      const dayStart = startOfDay(dayDate);
      const dayEnd = endOfDay(dayDate);

      const dayTransactions = allTransactions.filter((t) => {
        const tDate = new Date(t.date);
        return tDate >= dayStart && tDate <= dayEnd;
      });

      const dayInflow = dayTransactions
        .filter(isValidInflow)
        .reduce((sum, t) => sum + parseFloat(t.amount), 0);

      const dayOutflow = dayTransactions
        .filter((t) => t.direction === 'Out')
        .reduce((sum, t) => sum + parseFloat(t.amount), 0);

      dailyData.push({
        label: format(dayStart, 'MMM dd'),
        inflow: dayInflow,
        outflow: dayOutflow,
        net: dayInflow - dayOutflow,
      });
    }

    // Calculate weekly trend data (last 8 weeks)
    const weeklyData = [];
    for (let i = 7; i >= 0; i--) {
      const weekDate = subWeeks(new Date(), i);
      const weekStart = startOfWeek(weekDate, { weekStartsOn: 0 }); // Sunday
      const weekEnd = endOfWeek(weekDate, { weekStartsOn: 0 });

      const weekTransactions = allTransactions.filter((t) => {
        const tDate = new Date(t.date);
        return tDate >= weekStart && tDate <= weekEnd;
      });

      const weekInflow = weekTransactions
        .filter(isValidInflow)
        .reduce((sum, t) => sum + parseFloat(t.amount), 0);

      const weekOutflow = weekTransactions
        .filter((t) => t.direction === 'Out')
        .reduce((sum, t) => sum + parseFloat(t.amount), 0);

      weeklyData.push({
        label: format(weekStart, 'MMM dd'),
        inflow: weekInflow,
        outflow: weekOutflow,
        net: weekInflow - weekOutflow,
      });
    }

    // Calculate monthly trend data (last 6 months)
    const monthlyData = [];
    for (let i = 5; i >= 0; i--) {
      const monthDate = subMonths(new Date(), i);
      const monthStart = startOfMonth(monthDate);
      const monthEnd = endOfMonth(monthDate);

      const monthTransactions = allTransactions.filter((t) => {
        const tDate = new Date(t.date);
        return tDate >= monthStart && tDate <= monthEnd;
      });

      const monthInflow = monthTransactions
        .filter(isValidInflow)
        .reduce((sum, t) => sum + parseFloat(t.amount), 0);

      const monthOutflow = monthTransactions
        .filter((t) => t.direction === 'Out')
        .reduce((sum, t) => sum + parseFloat(t.amount), 0);

      monthlyData.push({
        label: format(monthStart, 'MMM yyyy'),
        inflow: monthInflow,
        outflow: monthOutflow,
        net: monthInflow - monthOutflow,
      });
    }

    // Loan type distribution
    const loanTypeData = [
      {
        name: 'Lot Title',
        value: allLoans.filter((l) => l.type === 'Lot Title').length,
        color: '#e8850c', // Primary Orange
      },
      {
        name: 'OR/CR',
        value: allLoans.filter((l) => l.type === 'OR/CR').length,
        color: '#7c6dcb', // Violet
      },
      {
        name: 'Agent',
        value: allLoans.filter((l) => l.type === 'Agent').length,
        color: '#dc6b6b', // Coral
      },
    ].filter((item) => item.value > 0);

    // Loan status distribution
    const fullyFundedLoans = allLoans.filter(
      (loan) => loan.status === 'Fully Funded',
    ).length;

    const partiallyFundedLoans = allLoans.filter(
      (loan) => loan.status === 'Partially Funded',
    ).length;

    const loanStatusData = [
      {
        name: 'Fully Funded',
        value: fullyFundedLoans,
        color: '#34b39a', // Teal
      },
      {
        name: 'Partially Funded',
        value: partiallyFundedLoans,
        color: '#d4a535', // Gold
      },
      {
        name: 'Completed',
        value: completedLoansCount,
        color: '#e8850c', // Amber
      },
      {
        name: 'Overdue',
        value: overdueLoansCount,
        color: '#dc6b6b', // Coral
      },
    ].filter((item) => item.value > 0);

    // Top investors by capital
    const investorCapitalData = allInvestors
      .map((inv) => {
        const stats = calculateInvestorStats(inv);
        return {
          name: inv.name,
          capital: stats.totalCapital,
          interest: stats.totalInterest,
        };
      })
      .sort((a, b) => b.capital - a.capital)
      .slice(0, 5);

    // Upcoming payments to send (unpaid loan investor transactions)
    const now = new Date();
    const unpaidLoanTransactions: Array<{
      id: number;
      loanId: number;
      loanName: string;
      loanType: LoanType;
      investorName: string;
      amount: string;
      sentDate: Date;
    }> = [];

    allLoans.forEach((loan) => {
      loan.loanInvestors
        .filter((li: any) => !li.isPaid)
        .forEach((li: any) => {
          unpaidLoanTransactions.push({
            id: li.id,
            loanId: loan.id,
            loanName: loan.loanName,
            loanType: loan.type,
            investorName: li.investor.name,
            amount: li.amount,
            sentDate: li.sentDate,
          });
        });
    });

    const upcomingPaymentsToSend = unpaidLoanTransactions.sort(
      (a, b) => new Date(a.sentDate).getTime() - new Date(b.sentDate).getTime(),
    );

    // Upcoming payments due (loans due within next 14 days, excluding completed/overdue)
    const fourteenDaysFromNow = addDays(now, 14);
    const upcomingPaymentsDue = allLoans
      .filter((loan) => {
        const dueDate = new Date(loan.dueDate);
        return (
          (loan.status === 'Fully Funded' ||
            loan.status === 'Partially Funded') &&
          isAfter(dueDate, now) &&
          isBefore(dueDate, fourteenDaysFromNow)
        );
      })
      .sort(
        (a, b) => new Date(a.dueDate).getTime() - new Date(b.dueDate).getTime(),
      );

    // Overdue loans (status overdue or past due date)
    const overdueLoansData = allLoans
      .filter(
        (loan) =>
          loan.status === 'Overdue' ||
          (loan.status !== 'Completed' && isPast(new Date(loan.dueDate))),
      )
      .sort(
        (a, b) => new Date(a.dueDate).getTime() - new Date(b.dueDate).getTime(),
      );

    return {
      // Overview stats
      totalPrincipal,
      completedPrincipal,
      completedInterestEarned,
      totalInterestExpected,
      activeLoansCount,
      overdueLoansCount,
      totalLoans: allLoans.length,
      completedLoansCount,
      totalInvestors,
      activeInvestors,
      totalInflow,
      totalOutflow,
      // Chart data
      dailyData,
      weeklyData,
      monthlyData,
      loanTypeData,
      loanStatusData,
      investorCapitalData,
      // Upcoming data
      upcomingPaymentsToSend,
      upcomingPaymentsDue,
      completedLoansData: [...completedLoansData].sort(
        (a, b) => new Date(b.dueDate).getTime() - new Date(a.dueDate).getTime(),
      ),
      overdueLoansData,
    };
  } catch (error) {
    console.error('Error fetching dashboard data:', error);
    return {
      totalPrincipal: 0,
      completedPrincipal: 0,
      completedInterestEarned: 0,
      totalInterestExpected: 0,
      activeLoansCount: 0,
      overdueLoansCount: 0,
      totalLoans: 0,
      completedLoansCount: 0,
      totalInvestors: 0,
      activeInvestors: 0,
      totalInflow: 0,
      totalOutflow: 0,
      dailyData: [],
      weeklyData: [],
      monthlyData: [],
      loanTypeData: [],
      loanStatusData: [],
      investorCapitalData: [],
      upcomingPaymentsToSend: [],
      upcomingPaymentsDue: [],
      completedLoansData: [],
      overdueLoansData: [],
    };
  }
}

const getDashboardData = unstable_cache(
  queryDashboardData,
  ['dashboard-data'],
  { revalidate: 300, tags: [CACHE_TAGS.dashboard] },
);

export default async function DashboardPage() {
  const session = await getCachedAuth();
  if (!session?.user?.id) {
    return null; // This should never happen due to middleware protection
  }

  const data = await getDashboardData(session.user.id);
  const totalEarnings = data.completedPrincipal + data.completedInterestEarned;
  const activePrincipal = data.totalPrincipal - data.completedPrincipal;
  const hasAnyActivity =
    data.upcomingPaymentsDue.length > 0 ||
    data.overdueLoansData.length > 0 ||
    data.upcomingPaymentsToSend.length > 0 ||
    data.completedLoansData.length > 0;

  return (
    <div className="space-y-8 md:space-y-10">
      <OverdueChecker />

      <PageHeader
        title="Dashboard"
        description="Overview of your lending performance and upcoming activity."
        eyebrow="Welcome back"
      />

      <SummaryCard
        metrics={[
          {
            label: 'Total Principal',
            amount: data.totalPrincipal,
            subCount: data.totalLoans,
            subCountSuffix: ' loans',
          },
          {
            label: 'Active',
            amount: activePrincipal,
            subCount: data.activeLoansCount,
            subCountSuffix: ' loans',
          },
          {
            label: 'Completed',
            amount: data.completedPrincipal,
            subCount: data.completedLoansCount,
            subCountSuffix: ' loans',
          },
          {
            label: 'Interest Earned',
            amount: data.completedInterestEarned,
            subValueTemplate: 'of {amount}',
            subAmount: data.totalInterestExpected,
            valueClassName: 'text-emerald-600 dark:text-emerald-500',
          },
          {
            label: 'Total Earnings',
            amount: totalEarnings,
            subValue: 'Completed + Interest Earned',
          },
        ]}
      />

      <section
        className={cn('space-y-4', !hasAnyActivity && 'hidden 2xl:block')}
      >
        <div>
          <p className="section-eyebrow">Activity</p>
          <h2 className="text-lg font-semibold tracking-tight">
            Needs attention
          </h2>
        </div>
        <DashboardActivityCards
          completedLoans={data.completedLoansData}
          overdueLoans={data.overdueLoansData}
          pendingDisbursements={data.upcomingPaymentsToSend}
          upcomingPaymentsDue={data.upcomingPaymentsDue}
        />
      </section>

      <section className="space-y-4">
        <div>
          <p className="section-eyebrow">Analytics</p>
          <h2 className="text-lg font-semibold tracking-tight">
            Trends & insights
          </h2>
        </div>
        <div
          className={`grid gap-5 ${SHOW_TRANSACTIONS_UI ? 'lg:grid-cols-2' : 'lg:grid-cols-1'}`}
        >
          {SHOW_TRANSACTIONS_UI && (
            <CashflowTrendChart
              dailyData={data.dailyData}
              weeklyData={data.weeklyData}
              monthlyData={data.monthlyData}
              title="Cashflow Trend"
              emptyMessage="No cashflow data"
            />
          )}

          {/* Top Investors by Capital */}
          <CurrencyBarChart
            data={data.investorCapitalData}
            title="Top Investors by Capital"
            xAxisKey="name"
            dataKeys={[
              {
                key: 'capital',
                label: 'Capital',
                color: '#e8850c', // Warm Amber
              },
              {
                key: 'interest',
                label: 'Interest',
                color: '#34b39a', // Teal
              },
            ]}
            emptyMessage="No investors found"
          />
        </div>
      </section>

      <section className="space-y-4">
        <div>
          <p className="section-eyebrow">Portfolio</p>
          <h2 className="text-lg font-semibold tracking-tight">Distribution</h2>
        </div>
        <div className="grid gap-5 lg:grid-cols-2">
          {/* Loan Type Distribution */}
          <LoanTypePieChart
            data={data.loanTypeData}
            title="Loan Type Distribution"
            emptyMessage="No loans found"
          />

          {/* Loan Status Distribution */}
          <LoanTypePieChart
            data={data.loanStatusData}
            title="Loan Status Distribution"
            emptyMessage="No loans found"
          />
        </div>
      </section>
    </div>
  );
}

// src/routes/dashboard/+page.svelte
<script lang="ts">
	import DashboardPage from '$lib/components/common/DashboardPage.svelte';
	import PageHeader from '$lib/components/PageHeader.svelte';
	import SummaryCard from '$lib/components/common/SummaryCard.svelte';
	import DashboardActivityCards from '$lib/components/common/DashboardActivityCards.svelte';
	import DashboardSummarySkeleton from '$lib/components/common/DashboardSummarySkeleton.svelte';
	import DashboardChartsSkeleton from '$lib/components/common/DashboardChartsSkeleton.svelte';
	import OverdueChecker from '$lib/components/common/OverdueChecker.svelte';
	import CashflowTrendChart from '$lib/components/charts/CashflowTrendChart.svelte';
	import CurrencyBarChart from '$lib/components/charts/CurrencyBarChart.svelte';
	import LoanTypePieChart from '$lib/components/charts/LoanTypePieChart.svelte';
	import { SHOW_TRANSACTIONS_UI } from '$lib/feature-flags';
	import { cn } from '$lib/utils';

	let { data } = $props();
</script>

<svelte:head><title>Dashboard</title></svelte:head>

<DashboardPage>
	<OverdueChecker />

	{#await data.summary}
		<DashboardSummarySkeleton />
	{:then summary}
		{@const totalEarnings = summary.completedPrincipal + summary.completedInterestEarned}
		{@const activePrincipal = summary.totalPrincipal - summary.completedPrincipal}
		{@const hasAnyActivity =
			summary.upcomingPaymentsDue.length > 0 ||
			summary.overdueLoansData.length > 0 ||
			summary.upcomingPaymentsToSend.length > 0 ||
			summary.completedLoansData.length > 0}

		<PageHeader
			title="Dashboard"
			description="Overview of your lending performance and upcoming activity."
			eyebrow="Welcome back"
			showPriceToggle={true}
		/>

		<SummaryCard
			metrics={[
				{
					label: 'Total Principal',
					amount: summary.totalPrincipal,
					subCount: summary.totalLoans,
					subCountSuffix: ' loans'
				},
				{
					label: 'Active',
					amount: activePrincipal,
					subCount: summary.activeLoansCount,
					subCountSuffix: ' loans'
				},
				{
					label: 'Completed',
					amount: summary.completedPrincipal,
					subCount: summary.completedLoansCount,
					subCountSuffix: ' loans'
				},
				{
					label: 'Interest Earned',
					amount: summary.completedInterestEarned,
					subValueTemplate: 'of {amount}',
					subAmount: summary.totalInterestExpected,
					valueClassName: 'text-emerald-600 dark:text-emerald-500'
				},
				{
					label: 'Total Earnings',
					amount: totalEarnings,
					subValue: 'Completed + Interest Earned'
				}
			]}
		/>

		<section class={cn('dashboard-section', !hasAnyActivity && 'hidden 2xl:block')}>
			<div class="dashboard-section-header">
				<div>
					<p class="section-eyebrow">Activity</p>
					<h2 class="dashboard-section-title">Needs attention</h2>
				</div>
			</div>
			<DashboardActivityCards
				completedLoans={summary.completedLoansData}
				overdueLoans={summary.overdueLoansData}
				pendingDisbursements={summary.upcomingPaymentsToSend}
				upcomingPaymentsDue={summary.upcomingPaymentsDue}
			/>
		</section>

		{#await data.charts}
			<DashboardChartsSkeleton />
		{:then charts}
			<section class="dashboard-section">
				<div>
					<p class="section-eyebrow">Analytics</p>
					<h2 class="dashboard-section-title">Trends & insights</h2>
				</div>
				<div class={cn('grid gap-3', SHOW_TRANSACTIONS_UI ? 'lg:grid-cols-2' : 'lg:grid-cols-1')}>
					{#if SHOW_TRANSACTIONS_UI}
						<CashflowTrendChart
							dailyData={charts.dailyData}
							weeklyData={charts.weeklyData}
							monthlyData={charts.monthlyData}
							title="Cashflow Trend"
							emptyMessage="No cashflow data"
						/>
					{/if}
					<CurrencyBarChart
						data={charts.investorCapitalData}
						title="Top Investors by Capital"
						emptyMessage="No investors found"
					/>
				</div>
			</section>

			<section class="dashboard-section">
				<div>
					<p class="section-eyebrow">Portfolio</p>
					<h2 class="dashboard-section-title">Distribution</h2>
				</div>
				<div class="grid gap-3 lg:grid-cols-2">
					<LoanTypePieChart
						data={charts.loanTypeData}
						title="Loan Type Distribution"
						emptyMessage="No loans found"
					/>
					<LoanTypePieChart
						data={charts.loanStatusData}
						title="Loan Status Distribution"
						emptyMessage="No loans found"
					/>
				</div>
			</section>
		{:catch}
			<p class="text-sm text-destructive">Charts failed to load</p>
		{/await}
	{:catch}
		<p class="text-sm text-destructive">Dashboard failed to load</p>
	{/await}
</DashboardPage>
